// Copied from @earendil-works/pi-coding-agent dist/utils/child-process (waitForChildProcess only) 0.85.1 (MIT License, (c) 2025 Mario Zechner; see LICENSE).
// Regenerated by scripts/sync-from-pi-repl.mjs; do not edit by hand.
import type { ChildProcess } from "node:child_process";
export declare function waitForChildProcess(child: ChildProcess): Promise<number | null>;
